version: 0.0.{build}
skip_non_tags: true
image: Visual Studio 2017
init:
  - ps: |
      $InfoVer = $env:APPVEYOR_REPO_TAG_NAME.TrimStart("v");
      $Ver = $InfoVer.Split("-")[0];
      Set-AppveyorBuildVariable -Name "InfomationalVersion" -Value $InfoVer
      Set-AppveyorBuildVariable -Name "FileVersion" -Value $Ver
      Update-AppveyorBuild -Version $InfoVer
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(FileVersion)
  assembly_file_version: $(FileVersion)
  assembly_informational_version: $(InfomationalVersion)
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(FileVersion)
  package_version: $(InfomationalVersion)
  assembly_version: $(FileVersion)
  file_version: $(FileVersion)
  informational_version: $(InfomationalVersion)
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
environment:
  Settings_json:
    secure: /UR89E50lwgR+LdOs5odndl61KDFLlUTSdwm2yUTt5pxyO+Vj+mipnVFvNYPSd0+phQGSww6zPWy2dmlQQdLioAmlJvGaly0uXNTH1eJPj0Qh8zpeEhhMZYfybPQiAkv3lyZ/YRMVkONpLY2QeruAnlbA5lY5qyxfVZ6eyvGWyGOCf0MvTnKBpaBNhfaMBsBwQWOagW6k3yYYpY9O199BlqsiM7ae856vk8E8tbD7B13CDVvyubmOQkPFTtuTOKn7UjEzUUfnOquC4bL8I/Zo+xVrYiCZsDAgyuP4QG7nteMK2b4NLxVp0/zi4zTvAdstVnon7O6kycEC0EFdRlosu3Iu+52mgl1Uvq2+bTYRQv//DqpTY+dOT6Uz04MvigCR1O86CfjvEEyGJnPLWm4MKMDehIqyJPmR05R4ga2rNU=
  NuGetToken:
    secure: 8U0FY4Wh+zyJriYPpUsyFXTmoc+upnrqrV3+u5mEkBCttmytqIqk3hQe475ck5aJ
test_script:
- ps: |
    cd $env:APPVEYOR_BUILD_FOLDER
    .\AppVeyor-Test-Deploy.ps1
artifacts:
- path: psCheckPoint.zip